FROM node:8.15.1-alpine

# Add OS-level dependencies
RUN apk add --no-cache git

# Add docpad at global
RUN npm install -g docpad@6.79.4

# Switch to regular user
USER node

# Install npm dependencies
COPY --chown=node package.json /app/package.json
WORKDIR /app
RUN npm install

# Build and test website
COPY --chown=node . /app
ENTRYPOINT npm run docpad
