[build]
  command = "npm run build"
  publish = "_site"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[dev]
  command = "npm run start"
  targetPort = 8080
  publish = "_site"
  autoLaunch = false
  framework = "#custom"
