env:
  DOCKER_IMAGE: "fluidprojectorg/infusion-docs"

# https://github.com/buildkite/feedback/issues/173
agent_tags: &agent_tags
  agents:
    name: "${BUILDKITE_AGENT_META_DATA_NAME?}"

steps:
  - name: "Build"
    command:
      - "docker build -t ${DOCKER_IMAGE} ."
    timeout_in_minutes: 5
    <<: *agent_tags

  - wait

  - name: "Release"
    command:
      - "docker push ${DOCKER_IMAGE}"
    branches: "master"
    timeout_in_minutes: 1
    <<: *agent_tags
