env:
  DOCKER_IMAGE: "fluidprojectorg/infusion-docs"

steps:
  - name: "Build"
    command:
      - "docker build -t ${DOCKER_IMAGE}:${BUILDKITE_COMMIT} ."
    timeout_in_minutes: 5

  - wait: ~
    continue_on_failure: true

  # This must be a separate stage so we only publish changes that were merged into the master branch
  - name: "Release"
    command:
      - "docker tag -t ${DOCKER_IMAGE}:latest ${DOCKER_IMAGE}:${BUILDKITE_COMMIT}"
      - "docker push ${DOCKER_IMAGE}:latest"
    branches: "master"

  - wait: ~
    continue_on_failure: true

  - name: "Cleanup"
    command:
      - "docker image rm -f ${DOCKER_IMAGE}"
